# TEAM INVITATION SYSTEM - FINAL DEPLOYMENT SCRIPT
# =================================================

Write-Host "🚀 Team Invitation System - Final Integration" -ForegroundColor Cyan
Write-Host ""

# Backend kompilieren
Write-Host "📦 Backend: mvn clean compile..." -ForegroundColor Yellow
cd "C:\Users\t13016a\Downloads\Team2\storeBackend"
$buildResult = mvn clean compile 2>&1 | Out-String
if ($LASTEXITCODE -eq 0) {
    Write-Host "✅ Backend BUILD SUCCESS" -ForegroundColor Green
} else {
    Write-Host "❌ Backend BUILD FAILED" -ForegroundColor Red
    Write-Host $buildResult
    exit 1
}

Write-Host ""
Write-Host "===========================================================================" -ForegroundColor Cyan
Write-Host "DEPLOYMENT STATUS REPORT" -ForegroundColor Cyan
Write-Host "===========================================================================" -ForegroundColor Cyan
Write-Host ""

Write-Host "✅ BACKEND VOLLSTÄNDIG IMPLEMENTIERT:" -ForegroundColor Green
Write-Host "  - TeamInvitationController (5 Endpoints + Preview)"
Write-Host "  - TeamInvitationService (Token-Hashing, Validation)"
Write-Host "  - EmailService (sendTeamInvitationEmail)"
Write-Host "  - email-templates/team-invitation.html"
Write-Host "  - Security: SHA-256, E-Mail-Match, One-Time-Use"
Write-Host ""

Write-Host "✅ FRONTEND SERVICES ERSTELLT:" -ForegroundColor Green
Write-Host "  - core/services/team-invitation.service.ts"
Write-Host "  - features/invitations/accept-invitation.component.ts"
Write-Host ""

Write-Host "⚠️ FRONTEND UI-INTEGRATION BENÖTIGT:" -ForegroundColor Yellow
Write-Host ""
Write-Host "Die folgenden Schritte müssen MANUELL abgeschlossen werden:"
Write-Host ""
Write-Host "1️⃣  STORE-ROLE-MANAGEMENT COMPONENT"
Write-Host "    Datei: storeBackend\storeFrontend\src\app\features\settings\store-role-management.component.ts"
Write-Host ""
Write-Host "    a) Import hinzufügen (Zeile 5):"
Write-Host "       import { TeamInvitationService } from '@app/core/services/team-invitation.service';"
Write-Host ""
Write-Host "    b) Constructor erweitern (Zeile ~450):"
Write-Host "       constructor("
Write-Host "         private roleService: RoleService,"
Write-Host "         private teamInvitationService: TeamInvitationService, // <-- NEU"
Write-Host "         private route: ActivatedRoute,"
Write-Host "         private router: Router"
Write-Host "       ) {}"
Write-Host ""
Write-Host "    c) Property hinzufügen (Zeile ~470):"
Write-Host "       pendingInvitations: TeamInvitation[] = [];"
Write-Host ""
Write-Host "    d) loadInvitations() Methode hinzufügen:"
Write-Host "       loadInvitations(): void {"
Write-Host "         if (!this.storeId) return;"
Write-Host "         this.teamInvitationService.getInvitations(this.storeId).subscribe({"
Write-Host "           next: invitations => this.pendingInvitations = invitations,"
Write-Host "           error: err => console.error('Failed to load invitations', err)"
Write-Host "         });"
Write-Host "       }"
Write-Host ""
Write-Host "    e) addMember() REAKTIVIEREN (Zeile 524-536 ersetzen):"
Write-Host "       addMember(): void {"
Write-Host "         if (!this.newMember.email || !this.newMember.role) {"
Write-Host "           this.showToast('E-Mail und Rolle sind erforderlich', 'error');"
Write-Host "           return;"
Write-Host "         }"
Write-Host "         this.saving = true;"
Write-Host "         this.teamInvitationService.createInvitation(this.storeId!, {"
Write-Host "           email: this.newMember.email,"
Write-Host "           role: this.newMember.role"
Write-Host "         }).subscribe({"
Write-Host "           next: () => {"
Write-Host "             this.showToast('Einladung erfolgreich versendet', 'success');"
Write-Host "             this.newMember = { userId: null, email: '', role: '', permissions: [] };"
Write-Host "             this.showAddForm = false;"
Write-Host "             this.loadInvitations();"
Write-Host "             this.saving = false;"
Write-Host "           },"
Write-Host "           error: err => {"
Write-Host "             this.showToast(err.error?.error || 'Einladung fehlgeschlagen', 'error');"
Write-Host "             this.saving = false;"
Write-Host "           }"
Write-Host "         });"
Write-Host "       }"
Write-Host ""
Write-Host "    f) TEMPLATE erweitern (nach Zeile 200):"
Write-Host "       <div class=\""section\">"
Write-Host "         <h2>📬 Offene Einladungen</h2>"
Write-Host "         <table class=\""table\"">"
Write-Host "           <thead>"
Write-Host "             <tr>"
Write-Host "               <th>E-Mail</th>"
Write-Host "               <th>Rolle</th>"
Write-Host "               <th>Status</th>"
Write-Host "               <th>Eingeladen am</th>"
Write-Host "               <th>Läuft ab</th>"
Write-Host "               <th>Aktionen</th>"
Write-Host "             </tr>"
Write-Host "           </thead>"
Write-Host "           <tbody>"
Write-Host "             <tr *ngFor=\""let inv of pendingInvitations\"">"
Write-Host "               <td>{{ inv.email }}</td>"
Write-Host "               <td>{{ inv.role }}</td>"
Write-Host "               <td><span [class]=\""'badge status-' + inv.status.toLowerCase()\"">"
Write-Host "                 {{ inv.status }}</span></td>"
Write-Host "               <td>{{ inv.createdAt | date }}</td>"
Write-Host "               <td>{{ inv.expiresAt | date }}</td>"
Write-Host "               <td>"
Write-Host "                 <button (click)=\""resendInvitation(inv.id)\"" *ngIf=\""inv.status === 'PENDING'\"">"
Write-Host "                   Erneut senden</button>"
Write-Host "                 <button (click)=\""revokeInvitation(inv.id)\"" *ngIf=\""inv.status === 'PENDING'\"">"
Write-Host "                   Widerrufen</button>"
Write-Host "               </td>"
Write-Host "             </tr>"
Write-Host "           </tbody>"
Write-Host "         </table>"
Write-Host "       </div>"
Write-Host ""
Write-Host "2️⃣  APP.ROUTES.TS"
Write-Host "    Datei: storeBackend\storeFrontend\src\app\app.routes.ts"
Write-Host ""
Write-Host "    Route hinzufügen:"
Write-Host "    {"
Write-Host "      path: 'invitations/accept',"
Write-Host "      loadComponent: () => import('./features/invitations/accept-invitation.component')"
Write-Host "        .then(m => m.AcceptInvitationComponent)"
Write-Host "    }"
Write-Host ""
Write-Host "3️⃣  i18n VERVOLLSTÄNDIGEN"
Write-Host "    Dateien: storeBackend\storeFrontend\src\assets\i18n\*.json"
Write-Host ""
Write-Host "    Kopiere de.json teamInvitation-Block nach:"
Write-Host "    - en.json (englisch übersetzen)"
Write-Host "    - fr.json (französisch übersetzen)"
Write-Host "    - ar.json (arabisch übersetzen, UTF-8)"
Write-Host ""
Write-Host "4️⃣  LOGIN RETURN-FLOW"
Write-Host "    Datei: storeBackend\storeFrontend\src\app\features\auth\login.component.ts"
Write-Host ""
Write-Host "    Im ngOnInit():"
Write-Host "    this.returnUrl = this.route.snapshot.queryParams['returnUrl'] || '/dashboard';"
Write-Host ""
Write-Host "    Nach erfolgreichem Login:"
Write-Host "    this.router.navigateByUrl(this.returnUrl);"
Write-Host ""
Write-Host "5️⃣  FRONTEND BUILD"
Write-Host "    cd storeBackend\storeFrontend"
Write-Host "    npm run build:prod"
Write-Host ""
Write-Host "===========================================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "📋 DEPLOYMENT CHECKLIST:" -ForegroundColor Yellow
Write-Host ""
Write-Host "Backend:"
Write-Host "  ✅ Controller mit Preview-Endpoint"
Write-Host "  ✅ Service mit Token-Hashing"
Write-Host "  ✅ E-Mail-Template"
Write-Host "  ✅ mvn clean compile SUCCESS"
Write-Host ""
Write-Host "Frontend:"
Write-Host "  ✅ TeamInvitationService erstellt"
Write-Host "  ✅ AcceptInvitationComponent erstellt"
Write-Host "  ✅ de.json aktualisiert"
Write-Host "  ⏳ Role Management UI (manuelle Integration)"
Write-Host "  ⏳ Route registrieren"
Write-Host "  ⏳ en/fr/ar i18n"
Write-Host "  ⏳ Login Return-Flow"
Write-Host "  ⏳ npm run build:prod"
Write-Host ""
Write-Host "Tests:"
Write-Host "  ⏳ E-Mail-Versand testen"
Write-Host "  ⏳ Accept-Flow testen (neu + bestehend)"
Write-Host "  ⏳ One-Time-Use testen"
Write-Host "  ⏳ Revoke testen"
Write-Host ""
Write-Host "===========================================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "📄 VOLLSTÄNDIGE DOKUMENTATION:" -ForegroundColor Cyan
Write-Host "   → TEAM_INVITATION_COMPLETE.md"
Write-Host ""
Write-Host "✅ Backend ist DEPLOYMENT-READY" -ForegroundColor Green
Write-Host "⚠️  Frontend UI-Integration manuell durchführen" -ForegroundColor Yellow
Write-Host ""
