-- H2-Compatible Schema for Local Development
-- Simplified version without PostgreSQL-specific DO blocks
-- For Production PostgreSQL, see scripts/db/schema.sql

-- Plans Tabelle (muss zuerst erstellt werden wegen FK)
CREATE TABLE IF NOT EXISTS plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    max_stores INTEGER NOT NULL,
    max_custom_domains INTEGER NOT NULL,
    max_subdomains INTEGER NOT NULL,
    max_storage_mb BIGINT NOT NULL,
    max_products INTEGER NOT NULL,
    max_image_count INTEGER NOT NULL
);

-- Initial Plans (synchronisiert mit PlanConfig.java)
MERGE INTO plans (name, max_stores, max_custom_domains, max_subdomains, max_storage_mb, max_products, max_image_count)
KEY (name)
VALUES
    ('FREE', 2, 0, 1, 1000, 100, 10),
    ('PRO', 4, 5, 10, 10000, 1000, 100),
    ('ENTERPRISE', -1, -1, -1, -1, -1, -1);

-- Users Tabelle
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    activation_email_sent_at TIMESTAMP,
    plan_id BIGINT,
    preferred_language VARCHAR(5) NOT NULL DEFAULT 'en',
    ai_calls_this_month INTEGER NOT NULL DEFAULT 0,
    ai_calls_period_start TIMESTAMP,
    CONSTRAINT fk_users_plan FOREIGN KEY (plan_id) REFERENCES plans(id)
);

-- Migration: Phone-Auth Support hinzufügen (H2-compatible)
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_number VARCHAR(20) UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS activation_email_sent_at TIMESTAMP;

-- Email Verifications Tabelle
CREATE TABLE IF NOT EXISTS email_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_email_verifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_email_verifications_token ON email_verifications(token);
CREATE INDEX IF NOT EXISTS idx_email_verifications_expires_at ON email_verifications(expires_at);

-- Password Reset Tokens Tabelle
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP,
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_token ON password_reset_tokens(token);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_expires_at ON password_reset_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_used_at ON password_reset_tokens(used_at);

-- Stores Tabelle
CREATE TABLE IF NOT EXISTS stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    owner_id BIGINT NOT NULL,
    description TEXT,
    logo_url TEXT,
    banner_image_url TEXT,
    slider_images TEXT,
    whatsapp_number VARCHAR(50),
    greeting_message TEXT,
    whatsapp_notifications_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    -- ─── Social Media & Kontakt-Links ─────────────────────
    contact_email VARCHAR(255),
    contact_phone VARCHAR(50),
    telegram_url TEXT,
    facebook_url TEXT,
    instagram_url TEXT,
    tiktok_url TEXT,
    footer_text TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stores_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);

-- ═══════════════════════════════════════════════════════════════════════════
-- MIGRATION: Währungs- und Steuerkonfiguration für Stores
-- ═══════════════════════════════════════════════════════════════════════════

-- Währungs- und Länder-Felder hinzufügen
ALTER TABLE stores ADD COLUMN IF NOT EXISTS currency_code VARCHAR(3);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS country_code VARCHAR(2);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS price_mode VARCHAR(10);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS vat_enabled BOOLEAN;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS default_tax_rate DECIMAL(5,2);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS shipping_tax_rate DECIMAL(5,2);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS shipping_tax_strategy VARCHAR(30);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS vat_exemption_text TEXT;

-- Bestehende Stores mit Defaults auffüllen (nur wenn NULL)
UPDATE stores SET currency_code = 'EUR' WHERE currency_code IS NULL;
UPDATE stores SET country_code = 'DE' WHERE country_code IS NULL;
UPDATE stores SET price_mode = 'GROSS' WHERE price_mode IS NULL;
UPDATE stores SET vat_enabled = TRUE WHERE vat_enabled IS NULL;
UPDATE stores SET default_tax_rate = 19.00 WHERE default_tax_rate IS NULL;
UPDATE stores SET shipping_tax_rate = 19.00 WHERE shipping_tax_rate IS NULL;
UPDATE stores SET shipping_tax_strategy = 'STORE_DEFINED' WHERE shipping_tax_strategy IS NULL;

-- NOT NULL Constraints setzen (erst nach Auffüllen!)
ALTER TABLE stores ALTER COLUMN currency_code SET NOT NULL;
ALTER TABLE stores ALTER COLUMN country_code SET NOT NULL;
ALTER TABLE stores ALTER COLUMN price_mode SET NOT NULL;
ALTER TABLE stores ALTER COLUMN vat_enabled SET NOT NULL;
ALTER TABLE stores ALTER COLUMN default_tax_rate SET NOT NULL;
ALTER TABLE stores ALTER COLUMN shipping_tax_rate SET NOT NULL;
ALTER TABLE stores ALTER COLUMN shipping_tax_strategy SET NOT NULL;

-- Defaults für neue Stores
ALTER TABLE stores ALTER COLUMN currency_code SET DEFAULT 'EUR';
ALTER TABLE stores ALTER COLUMN country_code SET DEFAULT 'DE';
ALTER TABLE stores ALTER COLUMN price_mode SET DEFAULT 'GROSS';
ALTER TABLE stores ALTER COLUMN vat_enabled SET DEFAULT TRUE;
ALTER TABLE stores ALTER COLUMN default_tax_rate SET DEFAULT 19.00;
ALTER TABLE stores ALTER COLUMN shipping_tax_rate SET DEFAULT 19.00;
ALTER TABLE stores ALTER COLUMN shipping_tax_strategy SET DEFAULT 'STORE_DEFINED';

-- Migration: Fehlende Spalten für bestehende stores-Tabellen hinzufügen
ALTER TABLE stores ADD COLUMN IF NOT EXISTS greeting_message TEXT;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(50);
ALTER TABLE stores ADD COLUMN IF NOT EXISTS telegram_url TEXT;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS facebook_url TEXT;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS instagram_url TEXT;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS tiktok_url TEXT;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS footer_text TEXT;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS business_type VARCHAR(20) NOT NULL DEFAULT 'SHOP';
ALTER TABLE stores ADD COLUMN IF NOT EXISTS opening_hours TEXT;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS google_maps_url TEXT;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS bot_protection_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS bot_protection_mode VARCHAR(20) NOT NULL DEFAULT 'SUSPICIOUS_ONLY';

-- Domains Tabelle
CREATE TABLE IF NOT EXISTS domains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    host VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(50) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    verification_token VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_domains_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

-- Store Usage Tracking
CREATE TABLE IF NOT EXISTS store_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL UNIQUE,
    storage_bytes BIGINT NOT NULL DEFAULT 0,
    image_count INTEGER NOT NULL DEFAULT 0,
    product_count INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_store_usage_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

-- ═══════════════════════════════════════════════════════════════════════════
-- Team Invitations Tabelle (Email-based invitation system with secure tokens)
-- ═══════════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS team_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    invited_by_user_id BIGINT NOT NULL,
    accepted_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    accepted_at TIMESTAMP,
    revoked_at TIMESTAMP,
    CONSTRAINT fk_team_invitations_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
    CONSTRAINT fk_team_invitations_invited_by FOREIGN KEY (invited_by_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_team_invitations_accepted_by FOREIGN KEY (accepted_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_team_invitations_status CHECK (status IN ('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED'))
);

-- Indexes für schnellere Lookups
CREATE INDEX IF NOT EXISTS idx_team_invitations_token_hash ON team_invitations(token_hash);
CREATE INDEX IF NOT EXISTS idx_team_invitations_store_email ON team_invitations(store_id, email);
CREATE INDEX IF NOT EXISTS idx_team_invitations_status ON team_invitations(status);
CREATE INDEX IF NOT EXISTS idx_team_invitations_expires_at ON team_invitations(expires_at);

-- Unique Constraint: nur eine PENDING-Einladung pro E-Mail und Store
CREATE UNIQUE INDEX IF NOT EXISTS idx_team_invitations_pending_unique
    ON team_invitations(store_id, email)
    WHERE status = 'PENDING';

-- User Roles (Join-Tabelle)
CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Subscriptions Tabelle
CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    plan VARCHAR(50) NOT NULL DEFAULT 'FREE',
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    start_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_date TIMESTAMP,
    renewal_date TIMESTAMP,
    payment_method VARCHAR(50),
    amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    billing_cycle VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',
    auto_renew BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Customer Profiles Tabelle
-- WICHTIG: user_id ist NICHT UNIQUE → ein User kann Kunde bei mehreren Stores sein (Multi-Tenant)
CREATE TABLE IF NOT EXISTS customer_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    external_source VARCHAR(50),
    external_id VARCHAR(100),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    phone VARCHAR(50),
    shipping_first_name VARCHAR(255),
    shipping_last_name VARCHAR(255),
    shipping_address1 VARCHAR(255),
    shipping_address2 VARCHAR(255),
    shipping_city VARCHAR(255),
    shipping_postal_code VARCHAR(50),
    shipping_country VARCHAR(100),
    shipping_phone VARCHAR(50),
    billing_first_name VARCHAR(255),
    billing_last_name VARCHAR(255),
    billing_address1 VARCHAR(255),
    billing_address2 VARCHAR(255),
    billing_city VARCHAR(255),
    billing_postal_code VARCHAR(50),
    billing_country VARCHAR(100),
    billing_phone VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_customer_profiles_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
    CONSTRAINT uq_customer_profile_user_store UNIQUE (user_id, store_id),
    CONSTRAINT uq_customer_profile_store_external UNIQUE (store_id, external_source, external_id)
);

-- Migration: Multi-Tenant Customer Profile Support
ALTER TABLE customer_profiles ADD COLUMN IF NOT EXISTS store_id BIGINT;
ALTER TABLE customer_profiles ADD COLUMN IF NOT EXISTS external_source VARCHAR(50);
ALTER TABLE customer_profiles ADD COLUMN IF NOT EXISTS external_id VARCHAR(100);
ALTER TABLE customer_profiles ADD CONSTRAINT IF NOT EXISTS fk_customer_profiles_store 
    FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE;
ALTER TABLE customer_profiles ADD CONSTRAINT IF NOT EXISTS uq_customer_profile_user_store 
    UNIQUE (user_id, store_id);
ALTER TABLE customer_profiles ADD CONSTRAINT IF NOT EXISTS uq_customer_profile_store_external 
    UNIQUE (store_id, external_source, external_id);

-- Customer Addresses
CREATE TABLE IF NOT EXISTS customer_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    address_type VARCHAR(20) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    company VARCHAR(255),
    address1 VARCHAR(255) NOT NULL,
    address2 VARCHAR(255),
    city VARCHAR(255) NOT NULL,
    state_province VARCHAR(100),
    postal_code VARCHAR(50) NOT NULL,
    country VARCHAR(100) NOT NULL,
    phone VARCHAR(50),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_addresses_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Media Tabelle
CREATE TABLE IF NOT EXISTS media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    minio_object_name VARCHAR(500) NOT NULL,
    media_type VARCHAR(50) NOT NULL,
    alt_text VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_media_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

-- ═══════════════════════════════════════════════════════════════════════════
-- MIGRATION: Steuerkonfiguration für Produkte
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE products ADD COLUMN IF NOT EXISTS tax_category VARCHAR(20);
ALTER TABLE products ADD COLUMN IF NOT EXISTS tax_rate DECIMAL(5,2);

-- Bestehende Produkte mit Defaults auffüllen
UPDATE products SET tax_category = 'STANDARD' WHERE tax_category IS NULL;
UPDATE products SET tax_rate = 19.00 WHERE tax_rate IS NULL;

-- NOT NULL Constraints
ALTER TABLE products ALTER COLUMN tax_category SET NOT NULL;
ALTER TABLE products ALTER COLUMN tax_rate SET NOT NULL;

-- Defaults für neue Produkte
ALTER TABLE products ALTER COLUMN tax_category SET DEFAULT 'STANDARD';
ALTER TABLE products ALTER COLUMN tax_rate SET DEFAULT 19.00;

-- Categories Tabelle
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    parent_id BIGINT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_categories_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE CASCADE,
    CONSTRAINT uk_category_slug_per_store UNIQUE (store_id, slug)
);

-- Products Tabelle
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT,
    category_id BIGINT,
    supplier_id BIGINT,
    title VARCHAR(255) NOT NULL,
    sku VARCHAR(100),
    description TEXT,
    base_price DECIMAL(10, 2) NOT NULL,
    wholesale_price DECIMAL(10, 2),
    is_supplier_catalog BOOLEAN DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    is_featured BOOLEAN DEFAULT FALSE,
    featured_order INTEGER DEFAULT 0,
    view_count BIGINT DEFAULT 0,
    sales_count BIGINT DEFAULT 0,
    average_rating DECIMAL(3, 2) DEFAULT 0.00,
    review_count INTEGER DEFAULT 0,
    stock INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_products_supplier FOREIGN KEY (supplier_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Product Options
CREATE TABLE IF NOT EXISTS product_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,  -- Hibernate-Entity: sortOrder -> sort_order
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_options_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Product Option Values (ElementCollection via ProductOption.values)
CREATE TABLE IF NOT EXISTS product_option_values (
    option_id BIGINT NOT NULL,
    option_value VARCHAR(100) NOT NULL,
    CONSTRAINT fk_product_option_values_option FOREIGN KEY (option_id) REFERENCES product_options(id) ON DELETE CASCADE
);

-- Product Variants
CREATE TABLE IF NOT EXISTS product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    sku VARCHAR(100) NOT NULL UNIQUE,
    barcode VARCHAR(100),
    price DECIMAL(10, 2) NOT NULL,
    compare_price DECIMAL(10, 2),
    cost_price DECIMAL(10, 2),
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    quantity INTEGER NOT NULL DEFAULT 0,
    weight DECIMAL(10, 3),
    option1 VARCHAR(255),
    option2 VARCHAR(255),
    option3 VARCHAR(255),
    image_url VARCHAR(500),
    media_urls TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    attributes_json TEXT,
    CONSTRAINT fk_product_variants_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Inventory Logs
CREATE TABLE IF NOT EXISTS inventory_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id BIGINT NOT NULL,
    quantity_change INTEGER NOT NULL,
    reason VARCHAR(50) NOT NULL,
    user_id BIGINT,
    notes TEXT,
    logged_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_logs_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Product Media
CREATE TABLE IF NOT EXISTS product_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    media_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT product_media_product_media_unique UNIQUE (product_id, media_id),
    CONSTRAINT fk_product_media_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_product_media_media FOREIGN KEY (media_id) REFERENCES media(id) ON DELETE CASCADE
);

-- Carts
CREATE TABLE IF NOT EXISTS carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255) UNIQUE,
    user_id BIGINT,
    store_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reminder_sent_at TIMESTAMP,
    CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_carts_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

-- Cart Items
CREATE TABLE IF NOT EXISTS cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    variant_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    price_snapshot DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts(id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE CASCADE
);

-- Phone Verifications
CREATE TABLE IF NOT EXISTS phone_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(50) NOT NULL,
    code VARCHAR(10) NOT NULL,
    store_id BIGINT NOT NULL,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    verified_at TIMESTAMP,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    channel VARCHAR(20),
    CONSTRAINT fk_phone_verifications_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

-- Orders Tabelle
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(50) NOT NULL UNIQUE,
    store_id BIGINT NOT NULL,
    customer_id BIGINT,
    customer_email VARCHAR(255),
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    tracking_number VARCHAR(100),
    tracking_carrier VARCHAR(50),
    tracking_url VARCHAR(500),
    total_amount DECIMAL(10, 2) NOT NULL,
    notes TEXT,
    payment_method VARCHAR(50),
    phone_verification_id BIGINT,
    phone_verified BOOLEAN NOT NULL DEFAULT FALSE,
    shipping_first_name VARCHAR(255),
    shipping_last_name VARCHAR(255),
    shipping_address1 VARCHAR(255),
    shipping_address2 VARCHAR(255),
    shipping_city VARCHAR(255),
    shipping_postal_code VARCHAR(50),
    shipping_country VARCHAR(100),
    shipping_phone VARCHAR(50),
    billing_first_name VARCHAR(255),
    billing_last_name VARCHAR(255),
    billing_address1 VARCHAR(255),
    billing_address2 VARCHAR(255),
    billing_city VARCHAR(255),
    billing_postal_code VARCHAR(50),
    billing_country VARCHAR(100),
    billing_phone VARCHAR(50),
    delivery_type VARCHAR(20),
    delivery_mode VARCHAR(20),
    delivery_provider_id BIGINT,
    delivery_fee DECIMAL(10, 2),
    eta_minutes INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    shipped_at TIMESTAMP,
    delivered_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    CONSTRAINT fk_orders_store FOREIGN KEY (store_id) REFERENCES stores(id),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES users(id)
);

-- Order Items
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    variant_id BIGINT,
    store_product_id BIGINT,
    supplier_id BIGINT,
    product_name VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    wholesale_price DECIMAL(10, 2),
    platform_fee_percentage DECIMAL(5, 4) DEFAULT 0.05,
    product_snapshot TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id)
);

-- ═══════════════════════════════════════════════════════════════════════════
-- MIGRATION: Steuer-Snapshot für Order Items
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE order_items ADD COLUMN IF NOT EXISTS tax_rate DECIMAL(5,2);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS tax_category VARCHAR(20);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS unit_price_net DECIMAL(15,2);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS unit_price_gross DECIMAL(15,2);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS line_net DECIMAL(15,2);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS line_tax DECIMAL(15,2);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS line_gross DECIMAL(15,2);

-- Bestehende OrderItems mit Defaults auffüllen
UPDATE order_items SET tax_rate = 19.00 WHERE tax_rate IS NULL;
UPDATE order_items SET tax_category = 'STANDARD' WHERE tax_category IS NULL;
UPDATE order_items SET unit_price_net = 0.00 WHERE unit_price_net IS NULL;
UPDATE order_items SET unit_price_gross = 0.00 WHERE unit_price_gross IS NULL;
UPDATE order_items SET line_net = 0.00 WHERE line_net IS NULL;
UPDATE order_items SET line_tax = 0.00 WHERE line_tax IS NULL;
UPDATE order_items SET line_gross = 0.00 WHERE line_gross IS NULL;

-- NOT NULL setzen (erst nach Auffüllen!)
ALTER TABLE order_items ALTER COLUMN tax_rate SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN tax_category SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN unit_price_net SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN unit_price_gross SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN line_net SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN line_tax SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN line_gross SET NOT NULL;

-- Defaults setzen
ALTER TABLE order_items ALTER COLUMN tax_rate SET DEFAULT 19.00;
ALTER TABLE order_items ALTER COLUMN tax_category SET DEFAULT 'STANDARD';
ALTER TABLE order_items ALTER COLUMN unit_price_net SET DEFAULT 0.00;
ALTER TABLE order_items ALTER COLUMN unit_price_gross SET DEFAULT 0.00;
ALTER TABLE order_items ALTER COLUMN line_net SET DEFAULT 0.00;
ALTER TABLE order_items ALTER COLUMN line_tax SET DEFAULT 0.00;
ALTER TABLE order_items ALTER COLUMN line_gross SET DEFAULT 0.00;

-- Bestehende Order Items mit Defaults auffüllen
UPDATE order_items SET tax_rate = 19.00 WHERE tax_rate IS NULL;
UPDATE order_items SET tax_category = 'STANDARD' WHERE tax_category IS NULL;

-- NOT NULL Constraints
ALTER TABLE order_items ALTER COLUMN tax_rate SET NOT NULL;
ALTER TABLE order_items ALTER COLUMN tax_category SET NOT NULL;

-- Defaults
ALTER TABLE order_items ALTER COLUMN tax_rate SET DEFAULT 19.00;
ALTER TABLE order_items ALTER COLUMN tax_category SET DEFAULT 'STANDARD';

-- Order Status History
CREATE TABLE IF NOT EXISTS order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    notes TEXT,
    CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_status_history_user FOREIGN KEY (updated_by) REFERENCES users(id)
);

-- Store Products (Marketplace)
CREATE TABLE IF NOT EXISTS store_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    supplier_product_id BIGINT NOT NULL,
    retail_price DECIMAL(10, 2) NOT NULL,
    margin_percentage DECIMAL(5, 4),
    is_active BOOLEAN DEFAULT TRUE,
    imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_store_product UNIQUE (store_id, supplier_product_id)
);

-- Commissions
CREATE TABLE IF NOT EXISTS commissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    recipient_type VARCHAR(20) NOT NULL,
    recipient_id BIGINT,
    amount DECIMAL(10, 2) NOT NULL,
    percentage DECIMAL(5, 4),
    status VARCHAR(20) DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP,
    paid_at TIMESTAMP,
    CONSTRAINT fk_commissions_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_commissions_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE
);

-- Platform Settings
CREATE TABLE IF NOT EXISTS platform_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT NOT NULL,
    description TEXT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Wishlists
CREATE TABLE IF NOT EXISTS wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL DEFAULT 'Meine Wunschliste',
    description TEXT,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    share_token VARCHAR(100) UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wishlists_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
    CONSTRAINT fk_wishlists_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Wishlist Items
CREATE TABLE IF NOT EXISTS wishlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wishlist_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    variant_id BIGINT,
    priority VARCHAR(20) DEFAULT 'MEDIUM',
    note TEXT,
    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wishlist_items_wishlist FOREIGN KEY (wishlist_id) REFERENCES wishlists(id) ON DELETE CASCADE,
    CONSTRAINT fk_wishlist_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_wishlist_items_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE SET NULL,
    CONSTRAINT wishlist_items_unique UNIQUE (wishlist_id, product_id, variant_id)
);

-- Saved Carts
CREATE TABLE IF NOT EXISTS saved_carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_saved_carts_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_carts_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Saved Cart Items
CREATE TABLE IF NOT EXISTS saved_cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saved_cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    variant_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    price_snapshot DECIMAL(10, 2) NOT NULL,
    product_snapshot TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_saved_cart_items_saved_cart FOREIGN KEY (saved_cart_id) REFERENCES saved_carts(id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_cart_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_cart_items_variant FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE CASCADE
);

-- Coupons
CREATE TABLE IF NOT EXISTS coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    code VARCHAR(100) NOT NULL,
    code_normalized VARCHAR(100) NOT NULL,
    type VARCHAR(20) NOT NULL,
    percent_discount INTEGER,
    value_cents BIGINT,
    currency VARCHAR(3),
    starts_at TIMESTAMP,
    ends_at TIMESTAMP,
    min_subtotal_cents BIGINT,
    applies_to VARCHAR(20) NOT NULL,
    domain_scope VARCHAR(20) NOT NULL,
    usage_limit_total INTEGER,
    usage_limit_per_customer INTEGER,
    times_used_total INTEGER NOT NULL DEFAULT 0,
    combinable VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    auto_apply BOOLEAN NOT NULL DEFAULT FALSE,
    description VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_coupons_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS coupon_product_ids (
    coupon_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    PRIMARY KEY (coupon_id, product_id),
    CONSTRAINT fk_coupon_product_ids_coupon FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS coupon_category_ids (
    coupon_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY (coupon_id, category_id),
    CONSTRAINT fk_coupon_category_ids_coupon FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS coupon_collection_ids (
    coupon_id BIGINT NOT NULL,
    collection_id BIGINT NOT NULL,
    PRIMARY KEY (coupon_id, collection_id),
    CONSTRAINT fk_coupon_collection_ids_coupon FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS coupon_customer_emails (
    coupon_id BIGINT NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    PRIMARY KEY (coupon_id, customer_email),
    CONSTRAINT fk_coupon_customer_emails_coupon FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS coupon_domain_ids (
    coupon_id BIGINT NOT NULL,
    domain_id BIGINT NOT NULL,
    PRIMARY KEY (coupon_id, domain_id),
    CONSTRAINT fk_coupon_domain_ids_coupon FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS coupon_redemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    coupon_id BIGINT NOT NULL,
    customer_id BIGINT,
    customer_email VARCHAR(255),
    order_id BIGINT NOT NULL,
    applied_cents BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    domain_host VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_coupon_redemptions_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
    CONSTRAINT fk_coupon_redemptions_coupon FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE CASCADE,
    CONSTRAINT fk_coupon_redemptions_customer FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Store Themes
CREATE TABLE IF NOT EXISTS store_themes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    template VARCHAR(50) NOT NULL,
    colors_json TEXT,
    typography_json TEXT,
    layout_json TEXT,
    custom_css TEXT,
    logo_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_store_themes_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

-- Homepage Sections (Homepage Builder)
CREATE TABLE IF NOT EXISTS homepage_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    section_type VARCHAR(50) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    settings TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_homepage_sections_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_homepage_sections_store ON homepage_sections(store_id);
CREATE INDEX IF NOT EXISTS idx_homepage_sections_sort ON homepage_sections(store_id, sort_order);

-- Redirect Rules
CREATE TABLE IF NOT EXISTS redirect_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    domain_id BIGINT,
    source_path VARCHAR(1000) NOT NULL,
    target_url VARCHAR(1000) NOT NULL,
    http_code INTEGER NOT NULL DEFAULT 301,
    is_regex BOOLEAN NOT NULL DEFAULT FALSE,
    priority INTEGER NOT NULL DEFAULT 100,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    comment VARCHAR(500),
    tag VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_redirect_rules_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
    CONSTRAINT fk_redirect_rules_domain FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE SET NULL
);

-- Audit Logs
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100),
    entity_id BIGINT,
    details TEXT,
    ip_address VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Store Delivery Settings
CREATE TABLE IF NOT EXISTS store_delivery_settings (
    store_id BIGINT PRIMARY KEY,
    pickup_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    delivery_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    express_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    currency VARCHAR(3) NOT NULL DEFAULT 'EUR',
    updated_at TIMESTAMP,
    CONSTRAINT fk_store_delivery_settings_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

-- Delivery Providers
CREATE TABLE IF NOT EXISTS delivery_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    priority INTEGER NOT NULL DEFAULT 100,
    config_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_delivery_providers_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

-- Delivery Zones
CREATE TABLE IF NOT EXISTS delivery_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    country VARCHAR(100) NOT NULL,
    city VARCHAR(100),
    postal_code_ranges TEXT,
    min_order_value DECIMAL(10, 2),
    fee_standard DECIMAL(10, 2) NOT NULL,
    fee_express DECIMAL(10, 2),
    eta_standard_minutes INTEGER NOT NULL,
    eta_express_minutes INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_delivery_zones_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

-- Store Slider Settings
CREATE TABLE IF NOT EXISTS store_slider_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL UNIQUE,
    override_mode VARCHAR(20) NOT NULL DEFAULT 'default_only',
    autoplay BOOLEAN NOT NULL DEFAULT true,
    duration_ms INTEGER NOT NULL DEFAULT 5000,
    transition_ms INTEGER NOT NULL DEFAULT 500,
    loop_enabled BOOLEAN NOT NULL DEFAULT true,
    show_dots BOOLEAN NOT NULL DEFAULT true,
    show_arrows BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_slider_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

-- Store Slider Images
CREATE TABLE IF NOT EXISTS store_slider_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    media_id BIGINT,
    image_url VARCHAR(500) NOT NULL,
    image_type VARCHAR(20) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    alt_text VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_slider_image_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
    CONSTRAINT fk_slider_image_media FOREIGN KEY (media_id) REFERENCES media(id) ON DELETE CASCADE
);

-- Default Slider Images
CREATE TABLE IF NOT EXISTS default_slider_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(100) NOT NULL DEFAULT 'general',
    image_url VARCHAR(500) NOT NULL,
    alt_text VARCHAR(255),
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- SEO Assets
CREATE TABLE IF NOT EXISTS seo_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    path VARCHAR(500) NOT NULL,
    size_bytes BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_seo_assets_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

-- SEO Settings
CREATE TABLE IF NOT EXISTS seo_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL UNIQUE,
    meta_title VARCHAR(255),
    meta_description VARCHAR(500),
    meta_keywords VARCHAR(500),
    og_image_url VARCHAR(1000),
    twitter_handle VARCHAR(100),
    robots_txt TEXT,
    sitemap_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    robots_index BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_seo_settings_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

-- Structured Data Templates
CREATE TABLE IF NOT EXISTS structured_data_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    template_json TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_structured_data_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

-- ==================================================================================
-- INDIZES für Performance
-- ==================================================================================

-- Stores
CREATE INDEX IF NOT EXISTS idx_stores_slug ON stores(slug);
CREATE INDEX IF NOT EXISTS idx_stores_owner ON stores(owner_id);

-- Domains
CREATE INDEX IF NOT EXISTS idx_domains_host ON domains(host);
CREATE INDEX IF NOT EXISTS idx_domains_store ON domains(store_id);

-- Categories
CREATE INDEX IF NOT EXISTS idx_categories_store ON categories(store_id);
CREATE INDEX IF NOT EXISTS idx_categories_parent ON categories(parent_id);
CREATE INDEX IF NOT EXISTS idx_categories_slug ON categories(slug);

-- Products
CREATE INDEX IF NOT EXISTS idx_products_store ON products(store_id);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_supplier ON products(supplier_id);
CREATE INDEX IF NOT EXISTS idx_products_catalog ON products(is_supplier_catalog);

-- Product Media
CREATE INDEX IF NOT EXISTS idx_product_media_product ON product_media(product_id);
CREATE INDEX IF NOT EXISTS idx_product_media_media ON product_media(media_id);

-- Carts
CREATE INDEX IF NOT EXISTS idx_carts_session_id ON carts(session_id);
CREATE INDEX IF NOT EXISTS idx_carts_user_id ON carts(user_id);
CREATE INDEX IF NOT EXISTS idx_carts_store_id ON carts(store_id);
CREATE INDEX IF NOT EXISTS idx_carts_expires_at ON carts(expires_at);
CREATE INDEX IF NOT EXISTS idx_carts_reminder_sent_at ON carts(reminder_sent_at);
CREATE INDEX IF NOT EXISTS idx_carts_updated_at ON carts(updated_at);

-- Cart Items
CREATE INDEX IF NOT EXISTS idx_cart_items_cart_id ON cart_items(cart_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_variant_id ON cart_items(variant_id);

-- Orders
CREATE INDEX IF NOT EXISTS idx_orders_store ON orders(store_id);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);

-- Order Items
CREATE INDEX IF NOT EXISTS idx_order_items_store_product ON order_items(store_product_id);
CREATE INDEX IF NOT EXISTS idx_order_items_supplier ON order_items(supplier_id);

-- User Roles
CREATE INDEX IF NOT EXISTS idx_user_roles_user ON user_roles(user_id);

-- Customer Profiles
CREATE INDEX IF NOT EXISTS idx_customer_profiles_user ON customer_profiles(user_id);

-- Customer Addresses
CREATE INDEX IF NOT EXISTS idx_customer_addresses_customer ON customer_addresses(customer_id);

-- Wishlists
CREATE INDEX IF NOT EXISTS idx_wishlists_customer ON wishlists(customer_id);
CREATE INDEX IF NOT EXISTS idx_wishlists_store ON wishlists(store_id);

-- Wishlist Items
CREATE INDEX IF NOT EXISTS idx_wishlist_items_wishlist ON wishlist_items(wishlist_id);
CREATE INDEX IF NOT EXISTS idx_wishlist_items_product ON wishlist_items(product_id);

-- Saved Carts
CREATE INDEX IF NOT EXISTS idx_saved_carts_customer ON saved_carts(customer_id);
CREATE INDEX IF NOT EXISTS idx_saved_carts_store ON saved_carts(store_id);

-- Saved Cart Items
CREATE INDEX IF NOT EXISTS idx_saved_cart_items_cart ON saved_cart_items(saved_cart_id);

-- Coupons
CREATE INDEX IF NOT EXISTS idx_coupon_store ON coupons(store_id);
CREATE INDEX IF NOT EXISTS idx_coupon_code ON coupons(store_id, code);
CREATE INDEX IF NOT EXISTS idx_coupon_status ON coupons(status);

-- Coupon Redemptions
CREATE INDEX IF NOT EXISTS idx_redemption_store ON coupon_redemptions(store_id);
CREATE INDEX IF NOT EXISTS idx_redemption_coupon ON coupon_redemptions(coupon_id);
CREATE INDEX IF NOT EXISTS idx_redemption_customer ON coupon_redemptions(customer_id);

-- Store Themes
CREATE INDEX IF NOT EXISTS idx_theme_store ON store_themes(store_id);

-- Inventory Logs
CREATE INDEX IF NOT EXISTS idx_inventory_logs_variant ON inventory_logs(variant_id);
CREATE INDEX IF NOT EXISTS idx_inventory_logs_timestamp ON inventory_logs(logged_at);

-- Redirect Rules
CREATE INDEX IF NOT EXISTS idx_redirect_store ON redirect_rules(store_id);
CREATE INDEX IF NOT EXISTS idx_redirect_domain ON redirect_rules(domain_id);
CREATE INDEX IF NOT EXISTS idx_redirect_active ON redirect_rules(is_active);
CREATE INDEX IF NOT EXISTS idx_redirect_priority ON redirect_rules(priority);

-- Store Products
CREATE INDEX IF NOT EXISTS idx_store_products_store ON store_products(store_id, is_active);
CREATE INDEX IF NOT EXISTS idx_store_products_supplier ON store_products(supplier_product_id);

-- Commissions
CREATE INDEX IF NOT EXISTS idx_commissions_order ON commissions(order_id);
CREATE INDEX IF NOT EXISTS idx_commissions_recipient ON commissions(recipient_type, recipient_id, status);
CREATE INDEX IF NOT EXISTS idx_commissions_status ON commissions(status);

-- Phone Verifications
CREATE INDEX IF NOT EXISTS idx_phone_number ON phone_verifications(phone_number);
CREATE INDEX IF NOT EXISTS idx_phone_created_at ON phone_verifications(created_at);
CREATE INDEX IF NOT EXISTS idx_phone_expires_at ON phone_verifications(expires_at);

-- SEO Assets
CREATE INDEX IF NOT EXISTS idx_seo_asset_store ON seo_assets(store_id);

-- Structured Data Templates
CREATE INDEX IF NOT EXISTS idx_struct_store_type ON structured_data_templates(store_id, type);

-- Subscriptions
CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_subscriptions_renewal ON subscriptions(renewal_date);

-- Delivery
CREATE INDEX IF NOT EXISTS idx_delivery_providers_store_active_priority ON delivery_providers(store_id, is_active, priority);
CREATE INDEX IF NOT EXISTS idx_delivery_zones_store_active ON delivery_zones(store_id, is_active);

-- Slider
CREATE INDEX IF NOT EXISTS idx_slider_images_store_id ON store_slider_images(store_id);
CREATE INDEX IF NOT EXISTS idx_slider_images_type ON store_slider_images(store_id, image_type);
CREATE INDEX IF NOT EXISTS idx_default_slider_category ON default_slider_images(category, is_active, display_order);

-- ==================================================================================
-- V10: DROPSHIPPING SYSTEM - PHASE 1 (H2 Compatible)
-- ==================================================================================
-- Dropshipping Sources (Supplier Links per Variant)
CREATE TABLE IF NOT EXISTS dropshipping_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant_id BIGINT NOT NULL,
    supplier_type VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    supplier_url VARCHAR(1000) NOT NULL,
    supplier_name VARCHAR(255),
    purchase_price DECIMAL(10, 2) NOT NULL CHECK (purchase_price >= 0),
    estimated_shipping_days INTEGER CHECK (estimated_shipping_days >= 0),
    supplier_sku VARCHAR(255),
    cj_product_id VARCHAR(255),
    cj_variant_id VARCHAR(255),
    notes CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,

    CONSTRAINT fk_dropshipping_sources_variant
        FOREIGN KEY (variant_id) REFERENCES product_variants(id) ON DELETE CASCADE,
    CONSTRAINT fk_dropshipping_sources_creator
        FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT uk_dropshipping_sources_variant
        UNIQUE (variant_id),
    CONSTRAINT check_supplier_type
        CHECK (supplier_type IN ('MANUAL', 'CJ'))
);

CREATE INDEX IF NOT EXISTS idx_dropshipping_sources_variant ON dropshipping_sources(variant_id);
CREATE INDEX IF NOT EXISTS idx_dropshipping_sources_creator ON dropshipping_sources(created_by);

-- Supplier Connections (API Tokens per Store)
CREATE TABLE IF NOT EXISTS supplier_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    supplier_type VARCHAR(20) NOT NULL,
    api_key VARCHAR(500),
    api_secret VARCHAR(500),
    access_token CLOB,
    refresh_token CLOB,
    token_expires_at TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_supplier_connections_store
        FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
    CONSTRAINT uk_supplier_connections_store_type
        UNIQUE (store_id, supplier_type),
    CONSTRAINT check_supplier_connection_type
        CHECK (supplier_type IN ('CJ', 'ALIEXPRESS', 'ALIBABA'))
);

CREATE INDEX IF NOT EXISTS idx_supplier_connections_store ON supplier_connections(store_id);
CREATE INDEX IF NOT EXISTS idx_supplier_connections_type ON supplier_connections(supplier_type);

-- Order Items Fulfillment Tracking
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS fulfillment_status VARCHAR(50) DEFAULT 'PENDING';
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS supplier_order_id VARCHAR(255);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS supplier_tracking_number VARCHAR(255);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS supplier_carrier VARCHAR(100);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS ordered_from_supplier_at TIMESTAMP;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS fulfilled_at TIMESTAMP;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS fulfillment_notes CLOB;

CREATE INDEX IF NOT EXISTS idx_order_items_fulfillment_status ON order_items(fulfillment_status);

-- ==================================================================================
-- Initial Data
-- ==================================================================================

-- FREE Plan
MERGE INTO plans (name, max_stores, max_custom_domains, max_subdomains, max_storage_mb, max_products, max_image_count)
KEY (name)
VALUES ('FREE', 1, 0, 1, 100, 50, 100);

-- Platform Settings
MERGE INTO platform_settings (setting_key, setting_value, description)
KEY (setting_key)
VALUES ('platform_fee_percentage', '0.05', 'Platform commission percentage (5%)');

MERGE INTO platform_settings (setting_key, setting_value, description)
KEY (setting_key)
VALUES ('recommended_reseller_margin', '0.30', 'Recommended reseller markup (30%)');

-- Default Slider Images
MERGE INTO default_slider_images (category, image_url, alt_text, display_order)
KEY (category, image_url)
VALUES
    ('general', 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=1200&h=400&fit=crop', 'Willkommen in unserem Shop', 1),
    ('general', 'https://images.unsplash.com/photo-1557821552-17105176677c?w=1200&h=400&fit=crop', 'Beste Angebote', 2),
    ('general', 'https://images.unsplash.com/photo-1523726491678-bf852e717f6a?w=1200&h=400&fit=crop', 'Premium Produkte', 3),
    ('fashion', 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=1200&h=400&fit=crop', 'Fashion Collection', 1),
    ('fashion', 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1200&h=400&fit=crop', 'Style & Trends', 2),
    ('electronics', 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&h=400&fit=crop', 'Tech Innovation', 1),
    ('electronics', 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=1200&h=400&fit=crop', 'Latest Gadgets', 2),
    ('food', 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&h=400&fit=crop', 'Frische Zutaten', 1),
    ('food', 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=1200&h=400&fit=crop', 'Leckere Gerichte', 2);

-- ==================== Wizard Progress Table ====================
-- Speichert den Fortschritt des Store-Creation-Wizards pro User
CREATE TABLE IF NOT EXISTS wizard_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    current_step INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    wizard_data TEXT,
    completed_steps TEXT DEFAULT '[]',
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    store_created BOOLEAN NOT NULL DEFAULT FALSE,
    created_store_id BIGINT,
    CONSTRAINT fk_wizard_progress_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_wizard_progress_store FOREIGN KEY (created_store_id) REFERENCES stores(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_wizard_progress_user ON wizard_progress(user_id);
CREATE INDEX IF NOT EXISTS idx_wizard_progress_status ON wizard_progress(status);
CREATE INDEX IF NOT EXISTS idx_wizard_progress_updated ON wizard_progress(last_updated);

-- =====================
-- V21: Store Banner Settings (Promo / Breaking-News Banner)
-- =====================
CREATE TABLE IF NOT EXISTS store_banner_settings (
    store_id BIGINT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    position VARCHAR(10) NOT NULL DEFAULT 'top',
    bg_color VARCHAR(30) NOT NULL DEFAULT '#667eea',
    text_color VARCHAR(30) NOT NULL DEFAULT '#ffffff',
    animation_speed INTEGER NOT NULL DEFAULT 60,
    texts_json TEXT DEFAULT '{"de":"🎉 Du erhältst heute Rabatt auf ausgewählte Produkte!","en":"🎉 Get a discount on selected products today!","ar":"🎉 احصل على خصم على منتجات مختارة اليوم!"}',
    icon VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_store_banner_settings_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_banner_store_id ON store_banner_settings(store_id);

-- =====================================================================================
-- STARTER PACKS (Vordefinierter Content für RESTAURANT / RIAD)
-- =====================================================================================
-- HINWEIS: Lokal ist spring.sql.init.mode=never → diese DDL/Seeds werden NICHT von
-- H2 ausgeführt. Hibernate erzeugt die Tabellen aus den Entities, das Seeding
-- übernimmt StarterPackSeeder.java. Dieser Block dient Produktions-/Doku-Parität.

-- products: direkte Bild-URL (Fallback, z.B. Starter-Pack-Default-Asset)
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url TEXT;

CREATE TABLE IF NOT EXISTS starter_pack (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    business_type VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS starter_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_starter_category_pack FOREIGN KEY (pack_id) REFERENCES starter_pack(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS starter_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id BIGINT NOT NULL,
    category_slug VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    base_price DECIMAL(10,2) NOT NULL,
    image_url TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_starter_product_pack FOREIGN KEY (pack_id) REFERENCES starter_pack(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS starter_carousel_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pack_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    alt_text VARCHAR(255),
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_starter_carousel_pack FOREIGN KEY (pack_id) REFERENCES starter_pack(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_starter_category_pack ON starter_category(pack_id);
CREATE INDEX IF NOT EXISTS idx_starter_product_pack ON starter_product(pack_id);
CREATE INDEX IF NOT EXISTS idx_starter_carousel_pack ON starter_carousel_item(pack_id);

-- ── Seed: Packs (idempotent über code) ───────────────────────────────────────
MERGE INTO starter_pack (code, business_type, name, description, is_active) KEY (code) VALUES
    ('RESTAURANT_MOROCCAN', 'RESTAURANT', 'Restaurant Marocain', 'Starter-Content für ein marokkanisches Restaurant.', TRUE),
    ('RIAD_MOROCCAN', 'RIAD', 'Riad Marocain', 'Starter-Content für ein marokkanisches Riad.', TRUE);

-- ── Seed: RESTAURANT_MOROCCAN Kategorien ─────────────────────────────────────
INSERT INTO starter_category (pack_id, name, slug, description, sort_order)
SELECT p.id, c.name, c.slug, c.description, c.sort_order
FROM (SELECT id FROM starter_pack WHERE code='RESTAURANT_MOROCCAN') p
CROSS JOIN (
    SELECT 'Petit déjeuner' name, 'petit-dejeuner' slug, 'Frühstücks-Spezialitäten' description, 1 sort_order
    UNION ALL SELECT 'Tajines','tajines','Traditionelle Tajine-Gerichte',2
    UNION ALL SELECT 'Couscous','couscous','Couscous-Variationen',3
    UNION ALL SELECT 'Grillades','grillades','Gegrilltes & Spieße',4
    UNION ALL SELECT 'Boissons','boissons','Getränke & Tee',5
    UNION ALL SELECT 'Desserts','desserts','Süße Spezialitäten',6
) c
WHERE NOT EXISTS (SELECT 1 FROM starter_category sc WHERE sc.pack_id = p.id);

-- ── Seed: RESTAURANT_MOROCCAN Produkte ───────────────────────────────────────
INSERT INTO starter_product (pack_id, category_slug, title, description, base_price, image_url, sort_order, is_featured)
SELECT p.id, x.category_slug, x.title, x.description, x.base_price, x.image_url, x.sort_order, x.is_featured
FROM (SELECT id FROM starter_pack WHERE code='RESTAURANT_MOROCCAN') p
CROSS JOIN (
    SELECT 'petit-dejeuner' category_slug, 'Petit déjeuner Marocain' title, 'Msemen, Beghrir, Olivenöl, Amlou, frisches Brot und Minztee.' description, 55.00 base_price, 'https://minio.markt.ma/store-assets/default-assets/restaurant/petit-dejeuner-marocain.jpg' image_url, 1 sort_order, TRUE is_featured
    UNION ALL SELECT 'tajines','Tajine Poulet Citron','Hähnchen mit eingelegten Zitronen, Oliven und Gewürzen.',75.00,'https://minio.markt.ma/store-assets/default-assets/restaurant/tajine-poulet-citron.jpg',2,TRUE
    UNION ALL SELECT 'tajines','Tajine Kefta','Hackbällchen in würziger Tomatensauce mit pochiertem Ei.',70.00,'https://minio.markt.ma/store-assets/default-assets/restaurant/tajine-kefta.jpg',3,FALSE
    UNION ALL SELECT 'couscous','Couscous Royal','Couscous mit Lamm, Hähnchen, Merguez und Gemüse.',95.00,'https://minio.markt.ma/store-assets/default-assets/restaurant/couscous-royal.jpg',4,TRUE
    UNION ALL SELECT 'boissons','Thé à la menthe','Traditioneller marokkanischer Minztee.',15.00,'https://minio.markt.ma/store-assets/default-assets/restaurant/the-a-la-menthe.jpg',5,FALSE
    UNION ALL SELECT 'desserts','Pastilla Poulet','Knusprige Pastilla mit Hähnchen, Mandeln und Zimt.',65.00,'https://minio.markt.ma/store-assets/default-assets/restaurant/pastilla-poulet.jpg',6,FALSE
) x
WHERE NOT EXISTS (SELECT 1 FROM starter_product sp WHERE sp.pack_id = p.id);

-- ── Seed: RESTAURANT_MOROCCAN Carousel ───────────────────────────────────────
INSERT INTO starter_carousel_item (pack_id, image_url, alt_text, sort_order)
SELECT p.id, x.image_url, x.alt_text, x.sort_order
FROM (SELECT id FROM starter_pack WHERE code='RESTAURANT_MOROCCAN') p
CROSS JOIN (
    SELECT 'https://minio.markt.ma/store-assets/default-assets/restaurant/hero-1.jpg' image_url, 'Cuisine marocaine authentique' alt_text, 1 sort_order
    UNION ALL SELECT 'https://minio.markt.ma/store-assets/default-assets/restaurant/hero-2.jpg','Tajines & Couscous faits maison',2
    UNION ALL SELECT 'https://minio.markt.ma/store-assets/default-assets/restaurant/hero-3.jpg','Ambiance chaleureuse',3
) x
WHERE NOT EXISTS (SELECT 1 FROM starter_carousel_item sci WHERE sci.pack_id = p.id);

-- ── Seed: RIAD_MOROCCAN Kategorien ───────────────────────────────────────────
INSERT INTO starter_category (pack_id, name, slug, description, sort_order)
SELECT p.id, c.name, c.slug, c.description, c.sort_order
FROM (SELECT id FROM starter_pack WHERE code='RIAD_MOROCCAN') p
CROSS JOIN (
    SELECT 'Chambres' name, 'chambres' slug, 'Zimmer' description, 1 sort_order
    UNION ALL SELECT 'Suites','suites','Suiten',2
    UNION ALL SELECT 'Petit déjeuner','petit-dejeuner','Frühstück',3
    UNION ALL SELECT 'Spa & Hammam','spa-hammam','Wellness',4
    UNION ALL SELECT 'Excursions','excursions','Ausflüge',5
    UNION ALL SELECT 'Services','services','Weitere Services',6
) c
WHERE NOT EXISTS (SELECT 1 FROM starter_category sc WHERE sc.pack_id = p.id);

-- ── Seed: RIAD_MOROCCAN Produkte ─────────────────────────────────────────────
INSERT INTO starter_product (pack_id, category_slug, title, description, base_price, image_url, sort_order, is_featured)
SELECT p.id, x.category_slug, x.title, x.description, x.base_price, x.image_url, x.sort_order, x.is_featured
FROM (SELECT id FROM starter_pack WHERE code='RIAD_MOROCCAN') p
CROSS JOIN (
    SELECT 'chambres' category_slug, 'Chambre Standard' title, 'Gemütliches Zimmer mit Blick auf den Innenhof.' description, 650.00 base_price, 'https://minio.markt.ma/store-assets/default-assets/riad/chambre-standard.jpg' image_url, 1 sort_order, TRUE is_featured
    UNION ALL SELECT 'suites','Suite Familiale','Geräumige Suite für Familien.',1200.00,'https://minio.markt.ma/store-assets/default-assets/riad/suite-familiale.jpg',2,TRUE
    UNION ALL SELECT 'petit-dejeuner','Petit déjeuner traditionnel','Marokkanisches Frühstück mit Msemen, Honig, Oliven und Minztee.',85.00,'https://minio.markt.ma/store-assets/default-assets/riad/petit-dejeuner-traditionnel.jpg',3,FALSE
    UNION ALL SELECT 'spa-hammam','Hammam Relax','Traditionelles Hammam mit schwarzer Seife und Gommage.',250.00,'https://minio.markt.ma/store-assets/default-assets/riad/hammam-relax.jpg',4,TRUE
    UNION ALL SELECT 'spa-hammam','Massage Argan','Entspannende Ganzkörpermassage mit Arganöl.',350.00,'https://minio.markt.ma/store-assets/default-assets/riad/massage-argan.jpg',5,FALSE
    UNION ALL SELECT 'excursions','Excursion Ourika','Tagesausflug ins Ourika-Tal inkl. Transport und Guide.',450.00,'https://minio.markt.ma/store-assets/default-assets/riad/excursion-ourika.jpg',6,FALSE
) x
WHERE NOT EXISTS (SELECT 1 FROM starter_product sp WHERE sp.pack_id = p.id);

-- ── Seed: RIAD_MOROCCAN Carousel ─────────────────────────────────────────────
INSERT INTO starter_carousel_item (pack_id, image_url, alt_text, sort_order)
SELECT p.id, x.image_url, x.alt_text, x.sort_order
FROM (SELECT id FROM starter_pack WHERE code='RIAD_MOROCCAN') p
CROSS JOIN (
    SELECT 'https://minio.markt.ma/store-assets/default-assets/riad/hero-1.jpg' image_url, 'Riad authentique au cœur de la médina' alt_text, 1 sort_order
    UNION ALL SELECT 'https://minio.markt.ma/store-assets/default-assets/riad/hero-2.jpg','Patio & piscine',2
    UNION ALL SELECT 'https://minio.markt.ma/store-assets/default-assets/riad/hero-3.jpg','Détente & bien-être',3
) x
WHERE NOT EXISTS (SELECT 1 FROM starter_carousel_item sci WHERE sci.pack_id = p.id);




-- ════════════════════════════════════════════════════════════════════════════
-- V25: security_events – Erweitert für Enums + Login-Tracking + IP-Details
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS security_events (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    request_id VARCHAR(100),
    
    -- Event Classification
    event_type VARCHAR(50),          -- Enum: LOGIN_SUCCESS, LOGIN_FAILED, REGISTRATION_ATTEMPT, etc.
    http_method VARCHAR(10),         -- POST, GET, PUT, DELETE
    http_status INTEGER,
    
    endpoint VARCHAR(200) NOT NULL,
    
    -- IP Information (Multi-Proxy-Support)
    client_ip VARCHAR(50),           -- Berechnete echte IP (IpAddressUtil)
    remote_addr VARCHAR(50),         -- Request.getRemoteAddr()
    x_forwarded_for VARCHAR(200),    -- X-Forwarded-For Header
    x_real_ip VARCHAR(50),           -- X-Real-IP Header (NGINX)
    
    user_agent VARCHAR(500),
    
    -- DSGVO-konforme Email-Felder
    email_masked VARCHAR(100),       -- te***@example.com
    email_hash VARCHAR(64),          -- SHA-256(email + pepper)
    email_domain VARCHAR(100),       -- example.com
    
    phone_masked VARCHAR(50),        -- +49***1234
    
    -- Protection Mechanisms
    captcha_present BOOLEAN,
    captcha_valid BOOLEAN,
    honeypot_triggered BOOLEAN,
    rate_limit_type VARCHAR(50),     -- Enum: IP, EMAIL, DOMAIN, PHONE, ENDPOINT
    
    blocked BOOLEAN NOT NULL DEFAULT false,
    block_reason VARCHAR(200),       -- Enum: CAPTCHA_INVALID, IP_RATE_LIMIT, etc.
    
    -- Mail-Related
    mail_type VARCHAR(50),           -- Enum: STORE_ACCESS, EMAIL_VERIFICATION, etc.
    mail_triggered BOOLEAN,          -- Mail wurde ausgelöst
    mail_sent BOOLEAN,               -- Mail tatsächlich versendet
    
    -- Emergency Controls
    kill_switch_triggered BOOLEAN,
    circuit_breaker_triggered BOOLEAN,
    
    -- Login-Tracking
    login_success BOOLEAN,           -- Bei Login-Events: true/false
    
    -- Bot Detection
    risk_score INTEGER,              -- 0-100 (optional)
    
    -- External Sources
    origin VARCHAR(200),             -- Origin-Header (CORS)
    referer VARCHAR(500),            -- Referer-Header
    
    -- Relations
    store_id BIGINT,
    user_id BIGINT,
    
    CONSTRAINT fk_security_events_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE SET NULL,
    CONSTRAINT fk_security_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Performance-Indizes für Grafana
CREATE INDEX IF NOT EXISTS idx_security_events_created_at ON security_events(created_at);
CREATE INDEX IF NOT EXISTS idx_security_events_endpoint ON security_events(endpoint);
CREATE INDEX IF NOT EXISTS idx_security_events_client_ip ON security_events(client_ip);
CREATE INDEX IF NOT EXISTS idx_security_events_blocked ON security_events(blocked);
CREATE INDEX IF NOT EXISTS idx_security_events_email_domain ON security_events(email_domain);
CREATE INDEX IF NOT EXISTS idx_security_events_event_type ON security_events(event_type);
CREATE INDEX IF NOT EXISTS idx_security_events_email_hash ON security_events(email_hash);
CREATE INDEX IF NOT EXISTS idx_security_events_mail_type ON security_events(mail_type);
CREATE INDEX IF NOT EXISTS idx_security_events_login_success ON security_events(login_success);

-- Composite Indizes für spezifische Queries
CREATE INDEX IF NOT EXISTS idx_security_events_login_analysis 
    ON security_events(endpoint, login_success, created_at) 
    WHERE endpoint = '/api/auth/login';

CREATE INDEX IF NOT EXISTS idx_security_events_mail_analysis 
    ON security_events(mail_type, mail_sent, created_at) 
    WHERE mail_sent = true;

-- ═══════════════════════════════════════════════════════════════════════════
-- MIGRATION: Währungs- und Steuer-Snapshots für Orders (UNVERÄNDERLICH!)
-- ═══════════════════════════════════════════════════════════════════════════

-- Währungs- und Länder-Felder
ALTER TABLE orders ADD COLUMN IF NOT EXISTS currency_code VARCHAR(3);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS price_mode VARCHAR(10);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS country_code VARCHAR(2);

-- Zwischensumme (Produkte ohne Versand)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal_net DECIMAL(15,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal_gross DECIMAL(15,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_total DECIMAL(15,2);

-- Versandkosten aufgeschlüsselt
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_net DECIMAL(15,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_tax DECIMAL(15,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_gross DECIMAL(15,2);

-- Gesamtsumme aufgeschlüsselt
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_net DECIMAL(15,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_gross DECIMAL(15,2);

-- Rabatt aufgeschlüsselt
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_net DECIMAL(15,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_tax DECIMAL(15,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_gross DECIMAL(15,2);

-- Bestehende Orders mit Defaults auffüllen
UPDATE orders SET currency_code = 'EUR' WHERE currency_code IS NULL;
UPDATE orders SET price_mode = 'GROSS' WHERE price_mode IS NULL;
UPDATE orders SET country_code = 'DE' WHERE country_code IS NULL;
UPDATE orders SET subtotal_net = 0.00 WHERE subtotal_net IS NULL;
UPDATE orders SET subtotal_gross = 0.00 WHERE subtotal_gross IS NULL;
UPDATE orders SET tax_total = 0.00 WHERE tax_total IS NULL;
UPDATE orders SET shipping_net = 0.00 WHERE shipping_net IS NULL;
UPDATE orders SET shipping_tax = 0.00 WHERE shipping_tax IS NULL;
UPDATE orders SET shipping_gross = 0.00 WHERE shipping_gross IS NULL;
UPDATE orders SET total_net = 0.00 WHERE total_net IS NULL;
UPDATE orders SET total_gross = 0.00 WHERE total_gross IS NULL;
UPDATE orders SET discount_net = 0.00 WHERE discount_net IS NULL;
UPDATE orders SET discount_tax = 0.00 WHERE discount_tax IS NULL;
UPDATE orders SET discount_gross = 0.00 WHERE discount_gross IS NULL;

-- NOT NULL für Pflichtfelder (erst nach Auffüllen!)
ALTER TABLE orders ALTER COLUMN currency_code SET NOT NULL;
ALTER TABLE orders ALTER COLUMN price_mode SET NOT NULL;
ALTER TABLE orders ALTER COLUMN country_code SET NOT NULL;

-- Defaults setzen
ALTER TABLE orders ALTER COLUMN currency_code SET DEFAULT 'EUR';
ALTER TABLE orders ALTER COLUMN price_mode SET DEFAULT 'GROSS';
ALTER TABLE orders ALTER COLUMN country_code SET DEFAULT 'DE';
ALTER TABLE orders ALTER COLUMN subtotal_net SET DEFAULT 0.00;
ALTER TABLE orders ALTER COLUMN subtotal_gross SET DEFAULT 0.00;
ALTER TABLE orders ALTER COLUMN tax_total SET DEFAULT 0.00;
ALTER TABLE orders ALTER COLUMN shipping_net SET DEFAULT 0.00;
ALTER TABLE orders ALTER COLUMN shipping_tax SET DEFAULT 0.00;
ALTER TABLE orders ALTER COLUMN shipping_gross SET DEFAULT 0.00;
ALTER TABLE orders ALTER COLUMN total_net SET DEFAULT 0.00;
ALTER TABLE orders ALTER COLUMN total_gross SET DEFAULT 0.00;
ALTER TABLE orders ALTER COLUMN discount_net SET DEFAULT 0.00;
ALTER TABLE orders ALTER COLUMN discount_tax SET DEFAULT 0.00;
ALTER TABLE orders ALTER COLUMN discount_gross SET DEFAULT 0.00;

-- ═══════════════════════════════════════════════════════════════════════════
-- MIGRATION: Coupon-Snapshot für Orders (UNVERÄNDERLICH!)
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE orders ADD COLUMN IF NOT EXISTS coupon_code_snapshot VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_type_snapshot VARCHAR(20);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_value_snapshot DECIMAL(15,2);

-- Kommentare für Dokumentation
COMMENT ON COLUMN orders.coupon_code_snapshot IS 'Snapshot des verwendeten Coupon-Codes (unveränderlich)';
COMMENT ON COLUMN orders.discount_type_snapshot IS 'Typ: PERCENT, FIXED, FREE_SHIPPING (unveränderlich)';
COMMENT ON COLUMN orders.discount_value_snapshot IS 'Wert bei PERCENT (Prozentsatz) oder FIXED (Betrag in Store-Währung)';

-- Constraints: Daten-Integrität auf DB-Ebene erzwingen
ALTER TABLE security_events
DROP CONSTRAINT IF EXISTS chk_mail_sent_not_when_blocked;

ALTER TABLE security_events
ADD CONSTRAINT chk_mail_sent_not_when_blocked
CHECK (
    mail_sent = FALSE
    OR blocked = FALSE
);

-- Dokumentation
COMMENT ON TABLE security_events IS 'Security Audit Log: CAPTCHA, Rate Limiting, Honeypot, Bot Protection, Login-Tracking';
COMMENT ON COLUMN security_events.email_masked IS 'DSGVO-konform: te***@example.com (nie volle E-Mail)';
COMMENT ON COLUMN security_events.email_hash IS 'SHA-256(normalized_email + server_pepper) für Analytics';
COMMENT ON COLUMN security_events.phone_masked IS 'DSGVO-konform: +49***1234 (nie volle Nummer)';
COMMENT ON COLUMN security_events.blocked IS 'true = Request blockiert, false = durchgelassen';
COMMENT ON COLUMN security_events.mail_triggered IS 'true = Request wollte eine E-Mail versenden (unabhängig ob blockiert)';
COMMENT ON COLUMN security_events.mail_sent IS 'true = E-Mail wurde TATSÄCHLICH erfolgreich versendet (nur wenn blocked=false)';
COMMENT ON COLUMN security_events.login_success IS 'Bei Login-Events: true = erfolgreich, false = fehlgeschlagen';

COMMENT ON CONSTRAINT chk_mail_sent_not_when_blocked ON security_events IS 
  'Verhindert inkonsistente Daten: blocked=true und mail_sent=true dürfen niemals gleichzeitig gesetzt sein.';

RAISE NOTICE '✅ V25: security_events erweitert';


-- =====================================================
-- V11: PAYPAL PAYMENT INTEGRATION - PHASE 1B
-- =====================================================

-- Payment Transactions (zentrale Payment-Tracking-Tabelle)
CREATE TABLE IF NOT EXISTS payment_transactions (
    id BIGSERIAL PRIMARY KEY,
    order_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'EUR',
    provider_order_id VARCHAR(100),
    provider_capture_id VARCHAR(100),
    provider_transaction_id VARCHAR(100),
    idempotency_key VARCHAR(100) NOT NULL,
    approved_at TIMESTAMP,
    paid_at TIMESTAMP,
    failed_at TIMESTAMP,
    failure_code VARCHAR(50),
    failure_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_payment_transactions_order 
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT uk_payment_transactions_idempotency 
        UNIQUE (idempotency_key),
    CONSTRAINT chk_payment_transactions_provider 
        CHECK (provider IN ('PAYPAL', 'STRIPE', 'BANK_TRANSFER', 'CASH_ON_DELIVERY')),
    CONSTRAINT chk_payment_transactions_status 
        CHECK (status IN ('PENDING', 'PENDING_APPROVAL', 'APPROVED', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED'))
);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_order ON payment_transactions(order_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_provider ON payment_transactions(provider);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_status ON payment_transactions(status);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_provider_order_id ON payment_transactions(provider_order_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_provider_capture_id ON payment_transactions(provider_capture_id);

-- Store Payment Configuration (Store-spezifische Provider-Konfiguration)
CREATE TABLE IF NOT EXISTS store_payment_configurations (
    id BIGSERIAL PRIMARY KEY,
    store_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    mode VARCHAR(10) NOT NULL DEFAULT 'SANDBOX',
    connection_status VARCHAR(20) NOT NULL DEFAULT 'NOT_CONNECTED',
    merchant_account_id VARCHAR(100),
    onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE,
    permissions_granted BOOLEAN NOT NULL DEFAULT FALSE,
    email_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    encrypted_credentials_ref TEXT,
    last_checked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_store_payment_configurations_store 
        FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
    CONSTRAINT uk_store_payment_provider 
        UNIQUE (store_id, provider),
    CONSTRAINT chk_store_payment_provider 
        CHECK (provider IN ('PAYPAL', 'STRIPE', 'BANK_TRANSFER', 'CASH_ON_DELIVERY')),
    CONSTRAINT chk_store_payment_mode 
        CHECK (mode IN ('SANDBOX', 'LIVE')),
    CONSTRAINT chk_store_payment_connection_status 
        CHECK (connection_status IN ('NOT_CONNECTED', 'PLATFORM_SANDBOX', 'CONNECTED', 'ERROR'))
);

CREATE INDEX IF NOT EXISTS idx_store_payment_configurations_store ON store_payment_configurations(store_id);
CREATE INDEX IF NOT EXISTS idx_store_payment_configurations_provider ON store_payment_configurations(provider);

-- Payment Webhook Events (Event-Deduplizierung und Audit-Trail)
CREATE TABLE IF NOT EXISTS payment_webhook_events (
    id BIGSERIAL PRIMARY KEY,
    provider VARCHAR(30) NOT NULL,
    provider_event_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    processing_status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    provider_order_id VARCHAR(100),
    provider_capture_id VARCHAR(100),
    payload_hash VARCHAR(64),
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    failure_code VARCHAR(50),
    failure_message TEXT,
    
    CONSTRAINT uk_payment_webhook_provider_event 
        UNIQUE (provider, provider_event_id),
    CONSTRAINT chk_payment_webhook_provider 
        CHECK (provider IN ('PAYPAL', 'STRIPE')),
    CONSTRAINT chk_payment_webhook_status 
        CHECK (processing_status IN ('RECEIVED', 'PROCESSING', 'PROCESSED', 'IGNORED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_payment_webhook_events_provider ON payment_webhook_events(provider);
CREATE INDEX IF NOT EXISTS idx_payment_webhook_events_status ON payment_webhook_events(processing_status);
CREATE INDEX IF NOT EXISTS idx_payment_webhook_events_provider_order ON payment_webhook_events(provider_order_id);
CREATE INDEX IF NOT EXISTS idx_payment_webhook_events_provider_capture ON payment_webhook_events(provider_capture_id);

-- Order Fulfillment Events (Idempotente Fulfillment-Tracking)
CREATE TABLE IF NOT EXISTS order_fulfillment_events (
    id BIGSERIAL PRIMARY KEY,
    order_id BIGINT NOT NULL,
    payment_transaction_id BIGINT,
    event_type VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    failure_code VARCHAR(50),
    failure_message TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMP,
    triggered_by VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_order_fulfillment_events_order 
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_fulfillment_events_payment 
        FOREIGN KEY (payment_transaction_id) REFERENCES payment_transactions(id) ON DELETE SET NULL,
    CONSTRAINT uk_order_fulfillment_event_type 
        UNIQUE (order_id, event_type),
    CONSTRAINT chk_order_fulfillment_event_type 
        CHECK (event_type IN ('ORDER_CONFIRMED', 'CONFIRMATION_EMAIL_SENT', 'ADMIN_NOTIFIED', 
                              'TELEGRAM_SENT', 'WHATSAPP_SENT', 'INVENTORY_REDUCED')),
    CONSTRAINT chk_order_fulfillment_status 
        CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_order_fulfillment_events_order ON order_fulfillment_events(order_id);
CREATE INDEX IF NOT EXISTS idx_order_fulfillment_events_payment ON order_fulfillment_events(payment_transaction_id);
CREATE INDEX IF NOT EXISTS idx_order_fulfillment_events_type ON order_fulfillment_events(event_type);
CREATE INDEX IF NOT EXISTS idx_order_fulfillment_events_status ON order_fulfillment_events(status);

-- Orders: Add checkout_token field for guest checkout security
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'orders' AND column_name = 'checkout_token'
    ) THEN
        ALTER TABLE orders ADD COLUMN checkout_token VARCHAR(36) UNIQUE;
        RAISE NOTICE 'Added checkout_token column to orders';
    END IF;
END $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- Payment-Status für PayPal und andere Online-Zahlungen
-- ═══════════════════════════════════════════════════════════════════════════
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'orders' AND column_name = 'payment_status'
    ) THEN
        ALTER TABLE orders ADD COLUMN payment_status VARCHAR(30);
        RAISE NOTICE 'Added payment_status column to orders';
    END IF;
END $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- Idempotenz-Flags für E-Mail und Inventory
-- Verhindert doppelte E-Mails/Bestandsreduzierungen bei Race Conditions
-- ═══════════════════════════════════════════════════════════════════════════
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'orders' AND column_name = 'confirmation_email_sent'
    ) THEN
        ALTER TABLE orders ADD COLUMN confirmation_email_sent BOOLEAN NOT NULL DEFAULT FALSE;
        RAISE NOTICE 'Added confirmation_email_sent column to orders';
    END IF;
END $$;

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'orders' AND column_name = 'inventory_adjusted'
    ) THEN
        ALTER TABLE orders ADD COLUMN inventory_adjusted BOOLEAN NOT NULL DEFAULT FALSE;
        RAISE NOTICE 'Added inventory_adjusted column to orders';
    END IF;
END $$;

