-- Flyway Migration V4: Add Delivery Management Tables
-- Created: 2026-01-30
-- Description: Tables for delivery providers, zones, and store delivery settings

-- Explizit public Schema setzen
SET search_path TO public;

-- Store Delivery Settings (One-to-One mit Store)
CREATE TABLE IF NOT EXISTS store_delivery_settings (
    store_id BIGINT PRIMARY KEY,
    pickup_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    delivery_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    express_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    currency VARCHAR(3) NOT NULL DEFAULT 'EUR',
    updated_at TIMESTAMP,
    FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

-- Delivery Providers
CREATE TABLE IF NOT EXISTS delivery_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    priority INTEGER NOT NULL DEFAULT 100,
    config_json TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_delivery_providers_store_active_priority ON delivery_providers(store_id, is_active, priority);

-- Delivery Zones
CREATE TABLE IF NOT EXISTS delivery_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    country VARCHAR(100) NOT NULL,
    city VARCHAR(100),
    postal_code_ranges TEXT,
    min_order_value DECIMAL(10, 2),
    fee_standard DECIMAL(10, 2) NOT NULL,
    fee_express DECIMAL(10, 2),
    eta_standard_minutes INTEGER NOT NULL,
    eta_express_minutes INTEGER,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_delivery_zones_store_active ON delivery_zones(store_id, is_active);

-- Comments for documentation
COMMENT ON TABLE store_delivery_settings IS 'Store-wide delivery configuration (pickup, delivery, express)';
COMMENT ON TABLE delivery_providers IS 'Delivery provider configurations (IN_HOUSE, WHATSAPP_DISPATCH, MANUAL, EXTERNAL)';
COMMENT ON TABLE delivery_zones IS 'Delivery zones with postal codes, fees, and ETAs';
COMMENT ON COLUMN orders.delivery_type IS 'PICKUP or DELIVERY';
COMMENT ON COLUMN orders.delivery_mode IS 'STANDARD or EXPRESS';
COMMENT ON COLUMN orders.delivery_provider_id IS 'Selected provider (auto-chosen by routing logic)';

